name: CI-CD Docker to Azure Functions

on:
  push:
    branches:
      - test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3️⃣ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4️⃣ Login to Azure Container Registry
      - name: Docker Login to ACR
        run: |
          az acr login --name ${{secrets.ACR_NAME}}
 
      # 5️⃣ Build Docker image
      - name: Build Docker Image
        run: |
          docker build -f Dockerfile -t ${{ secrets.ACR_NAME }}.azurecr.io/my-function-app:${{ github.sha }} .

      # 6️⃣ Push Docker image to ACR
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/my-function-app:${{ github.sha }}

      # 7️⃣ Deploy Docker image to Azure Function App
      - name: Deploy to Azure Function
        run: |
          az functionapp config container set \
            --name ${{ secrets.FUNCTION_APP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --image ${{ secrets.ACR_NAME }}.azurecr.io/my-function-app:${{ github.sha }} \
            --registry-server https://${{ secrets.ACR_NAME }}.azurecr.io \
            --registry-username ${{ secrets.CLIENT_ID }} \
            --registry-password ${{ secrets.CLIENT_SECRET }}

      # 8️⃣ Restart Azure Function App
      - name: Restart Function App
        run: |
          az functionapp restart --name ${{ secrets.FUNCTION_APP_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --runtime custom 
